
export const bbcodTestCases = [
  {
    id: 'blank',
    test: '',
  },
  {
    id: 'newlines',
    test: 'multiple lines\nnew line\n\n\n3 blank lines\n'},
//   {
//     id: 'headers',
//     test: '[h1]h1[/h1]\n[h2]h2[/h2]\nnormal\n',
//   }, Not supported
  {
    id: 'color',
    test: '[highlight=#b2b200][color=#0066cc]color[/color][/highlight]',
  },
  {
    id: 'color2',
    test: '[color=#6b24b2]purple[/color][color=#e60000]red[/color][highlight=#b2b200][color=#e60000]WithYellowBG[/color][/highlight][highlight=#b2b200][color=#66a3e0]NOW_BLUE_TEXT[/color][/highlight]',
  },
  {
    id: 'color_rainbow',
    test: '[highlight=#cce0f5]           [/highlight][highlight=#cce0f5][color=#e60000]I [/color][/highlight][highlight=#cce0f5][color=#ff9900]AM[/color][/highlight][highlight=#cce0f5][color=#ffff00] A[/color][/highlight][highlight=#cce0f5][color=#66b966] R[/color][/highlight][highlight=#cce0f5][color=#cce8cc]AI[/color][/highlight][highlight=#cce0f5][color=#0066cc]NB[/color][/highlight][highlight=#cce0f5][color=#9933ff]OW[/color][/highlight][highlight=#cce0f5][color=#ffffff]         [/color][/highlight]\n[highlight=#cce0f5][color=#ffffff]                                                 [/color][/highlight]\n[highlight=#facccc]Did you see a rainbow in sky? [/highlight]',
  },
  {
    id: 'space',
    test: '[highlight=#cce0f5]                  space    around               [/highlight]\n[highlight=#cce0f5]                                                          [/highlight]',
  },
  {
    id: 'color_fontsize',
    test: '[color=#9933ff][size=huge]Huge Purple[/size][/color][highlight=#facccc][color=#0047b2][size=small]Small Blue[/size][/color][/highlight]',
  },
  {
    id: 'bold',
    test: 'There is some [b]Bold[/b] text',
  },
  {
    id: 'italic',
    test: 'there is some [i]italic [/i]text',
  },
  {
    id: 'italic_bold',
    test: 'there is some [b][i]italic and bold [/i][/b]text',
  },
  {
    id: 'underscore',
    test: 'Text with [u]Underscore[/u] lol \n[u]there is some [/u][b][i][u]italic and bold [/u][/i][/b][u]text[/u]',
  },
  {
    id: 'underscore_strikethrough',
    test: 'Text with [s][u]Underscore strikethrough  [/u][/s]   lol\n[u]there is some [/u][b][i][u]italic and bold [/u][/i][/b][u]text[/u]',
  },
  {
    id: 'quote',
    test: '[blockquote]quote[/blockquote]\nNot quote',
  },
  /* IMPORTANT: multiline quote render differently on the old sosad website and the current textEditor.
  * when we have a multiline quote, the old sosad editor will do
  *                  [blockquote]line1 \n line2[/blockquote]
  * but the quill editor will force to start a new blockquote when a new line starts:
  *                  [blockquote]line1[/blockquote]
  *                  [blockquote]line2[/blockquote]
  * in the old sosad website, there will be margin between two blockquote, so they will render differently
  * as this is how Quill handles quote, fixing quill may be hard. It should be easier to ajust the old website's css.
  * the old bbcode document generated by the old sosad website should render fine in the new editor, but the bbcode generated by the new editor may look weird in the old site, which can be fixed by modify blockquote css margin.
  */
  {
    id: 'multiline_quote',
    test: '[blockquote]mutline\nis not working[/blockquote][blockquote]quote[/blockquote]\nnot quote',
  },
  {
    id: 'list',
    test: '[ol][li]number list[/li]\n[li]l2[/li]\n[li]l3[/li]\n[/ol]\n\n[ul][li]unorder list[/li]\n[li]l2[/li]\n[li]l3[/li]\n[/ul]',
  },
  {
    id: 'nested-list',
    test: '[ol][li]fsaf[/li]\n[li=indent-1]fsdf[/li]\n[li=indent-1]fsd[/li]\n[li=indent-2]sdf[/li]\n[li=indent-1]fsdf[/li]\n[li]fsdfs[/li]\n[/ol]',
  },
  {
    id: 'nested-ulist',
    test: '[ul][li]fsdf[/li]\n[li]fsdf[/li]\n[li=indent-1]fsdf[/li]\n[li=indent-2]fsdf[/li]\n[li=indent-1]fsdf[/li]\n[li]fsdf[/li]\n[/ul]',
  },
  {
    id: 'list-with-style',
    test: '[ul][li][color=#9933ff]fsdf[/color][/li]\n[li][highlight=#facccc]fsdf[/highlight][/li]\n[li=indent-1][b]fsdf[/b][/li]\n[li=indent-2][i]fsdf[/i][/li][li=indent-1][s]fsdf[/s][/li]\n[li]fsdf[/li]\n[/ul]',
  },
  {
    id: 'link',
    test: '[url=https://www.google.com/]link[/url]',
  },
  {
    id: 'img',
    test: '[img]https://images.unsplash.com/photo-1499084732479-de2c02d45fcc?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1000&amp;q=80[/img]\n',
  },
  {
    id: 'code',
    test: '[code]let a = 1;\nlet b = 2;\nfor (let i = 0; i < b; i++){\n  console.log("hello world");\n}\n[/code]',
  },
];